repos:
  - repo: local
    hooks:
      - id: cargo formatting
        name: cargo formatting
        description: Check if all files follow the rustfmt style
        # Using nightly build to get access to import ordering functionality.
        entry: cargo +nightly fmt --all
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: cargo clippy
        name: cargo clippy
        description: Check if all files follow cargo clippy style
        entry: cargo clippy -- -D warnings
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: cargo testing
        name: cargo testing
        description: Test entire workspace
        entry: cargo nextest run --workspace
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: cargo build
        name: cargo build
        description: Build entire workspace
        entry: cargo build --workspace
        language: system
        pass_filenames: false
