[workspace]
members = ["configuration"]

[package]
name = "slack-gcal-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.215", features = ["derive"]}
configuration = { path = "configuration"}