refresh_rate: 120 seconds

appenders:
    stdout:
        kind: console
        encoder:
            pattern: "{d(%+)(utc)} [{f}:{L}] {h({l})} {M}:{m}{n}"
        filters:
            - kind: threshold
              level: info
    rollingfile:
        kind: rolling_file
        path: "logs/slack-gcal-sync.log"
        encoder:
            kind: json
        policy:
            kind: compound
            trigger:
                kind: size
                limit: 10mb
            roller:
                kind: fixed_window
                pattern: "logs/slack-gcal-sync-{}.log"
                base: 0
                count: 5
root:
    level: info
    appenders:
        - stdout
        - rollingfile