[package]
name = "configuration"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
thiserror = "2.0.6"
serde_json = "1.0.133"
tempfile = "3.14.0"
